### ISSUE TITLE
Configuração inicial do travis-ci

### ISSUE THREAD

**Issue by fernandoe** [fernandoe/fe-arquivo-server#2]
- Registrar o repositório: https://travis-ci.org
- Adicionar `README.md` com o badge do build
- Adicionar `Makefile`
```make
install:
	pip install -r requirements.txt

test:
	cd ./source && python manage.py test
```
- Adicionar arquivo `.travis.yml`
```yml
language: python
python:
  - 3.6
install:
  - make install
script:
  - make test
```
- Comitar
